import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LayoutModule } from '@angular/cdk/layout';
import { OverlayModule } from '@angular/cdk/overlay';
import { FlexLayoutModule } from '@angular/flex-layout';

import {
    MatButtonModule,
    MatToolbarModule,
    MatSidenavModule,
    MatInputModule,
    MatFormFieldModule,
    MatDividerModule,
    MatListModule,
    MatTabsModule,
    MatCardModule,
    MatChipsModule,
    MatDialogModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSnackBarModule,
    MatStepperModule,
    MatTooltipModule,
    MatTableModule,
    MatPaginatorModule,
    MatSelectModule,
    MatExpansionModule,
    MatGridListModule,
    MatSlideToggleModule,
    MatProgressSpinnerModule,
    MatBottomSheetModule,
    MatSliderModule,
    MatAutocompleteModule,
    MatMenuModule,
    MatCheckboxModule,
    MatButtonToggleModule,
    MatIconModule,
    MatBadgeModule,
    MatRippleModule,
    MatProgressBarModule,
    MatRadioModule,
} from '@angular/material';
import {DragDropModule} from '@angular/cdk/drag-drop';

@NgModule({
    imports: [
        CommonModule,
        MatButtonModule,
        MatToolbarModule,
        MatSidenavModule,
        MatInputModule,
        MatFormFieldModule,
        MatDividerModule,
        MatListModule,
        MatTabsModule,
        MatCardModule,
        MatChipsModule,
        MatDialogModule,
        MatProgressBarModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatSnackBarModule,
        MatStepperModule,
        MatTooltipModule,
        MatTableModule,
        MatPaginatorModule,
        MatSelectModule,
        MatExpansionModule,
        MatGridListModule,
        MatSlideToggleModule,
        LayoutModule,
        MatProgressSpinnerModule,
        MatBottomSheetModule,
        MatSliderModule,
        MatAutocompleteModule,
        MatMenuModule,
        MatCheckboxModule,
        MatButtonToggleModule,
        OverlayModule,
        MatIconModule,
        MatBadgeModule,
        MatRippleModule,
        MatRadioModule,
        DragDropModule,
        FlexLayoutModule
    ],
    exports: [
        MatButtonModule,
        MatToolbarModule,
        MatSidenavModule,
        MatInputModule,
        MatFormFieldModule,
        MatDividerModule,
        MatListModule,
        MatTabsModule,
        MatCardModule,
        MatChipsModule,
        MatDialogModule,
        MatProgressBarModule,
        MatDatepickerModule,
        MatSnackBarModule,
        MatStepperModule,
        MatTooltipModule,
        MatTableModule,
        MatPaginatorModule,
        MatSelectModule,
        MatExpansionModule,
        MatGridListModule,
        MatSlideToggleModule,
        LayoutModule,
        MatProgressSpinnerModule,
        MatBottomSheetModule,
        MatSliderModule,
        MatAutocompleteModule,
        MatMenuModule,
        MatCheckboxModule,
        MatButtonToggleModule,
        OverlayModule,
        MatIconModule,
        MatBadgeModule,
        MatRippleModule,
        MatRadioModule,
        DragDropModule,
        FlexLayoutModule
    ],
    declarations: []
})
export class MaterialModule { }
